# Generated by Django 4.2.9 on 2026-07-22 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_camera_permission_role_site_cameracredential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=512)),
                ('thumb_key', models.CharField(blank=True, max_length=512)),
                ('taken_at', models.DateTimeField(db_index=True)),
                ('content_type', models.CharField(default='image/jpeg', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('storage', models.CharField(choices=[('seaweed', 'SeaweedFS (local VPS)'), ('r2', 'Cloudflare R2')], db_index=True, default='seaweed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.camera')),
            ],
            options={
                'verbose_name': 'Ảnh media',
                'verbose_name_plural': 'Ảnh media',
                'ordering': ('-taken_at',),
                'indexes': [models.Index(fields=['camera', '-taken_at'], name='core_media_camera__2b8e23_idx')],
            },
        ),
    ]
