# Generated by Django 4.2.9 on 2026-07-22 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang nén'), ('ready', 'Sẵn sàng tải'), ('failed', 'Thất bại'), ('expired', 'Đã hết hạn')], db_index=True, default='pending', max_length=16)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('media_ids', models.JSONField(blank=True, default=list)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('zip_key', models.CharField(blank=True, max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.camera')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gói tải ảnh',
                'verbose_name_plural': 'Gói tải ảnh',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MediaDayStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_stats', to='core.camera')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.media')),
            ],
            options={
                'verbose_name': 'Thống kê ảnh theo ngày',
                'verbose_name_plural': 'Thống kê ảnh theo ngày',
                'ordering': ('-day',),
                'indexes': [models.Index(fields=['camera', '-day'], name='core_mediad_camera__e176c8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediadaystat',
            constraint=models.UniqueConstraint(fields=('camera', 'day'), name='uniq_media_daystat_camera_day'),
        ),
        migrations.AddIndex(
            model_name='mediaarchive',
            index=models.Index(fields=['requested_by', '-created_at'], name='core_mediaa_request_3ef099_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaarchive',
            index=models.Index(fields=['status', 'expires_at'], name='core_mediaa_status_4f1109_idx'),
        ),
    ]
