# Generated by Django 4.2.30 on 2026-07-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediaarchive_mediadaystat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('-taken_at',), 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='mediaarchive',
            options={'ordering': ('-created_at',), 'verbose_name': 'Media archive', 'verbose_name_plural': 'Media archives'},
        ),
        migrations.AlterModelOptions(
            name='mediadaystat',
            options={'ordering': ('-day',), 'verbose_name': 'Daily media stats', 'verbose_name_plural': 'Daily media stats'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role permission', 'verbose_name_plural': 'Role permissions'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='usercameraaccess',
            options={'verbose_name': 'Camera access', 'verbose_name_plural': 'Camera accesses'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User role', 'verbose_name_plural': 'User roles'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='cameracredential',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaarchive',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_interval_sec', models.PositiveIntegerField(default=3600, help_text='Chu kỳ chụp ảnh (giây).')),
                ('wake_requested_at', models.DateTimeField(blank=True, help_text='Thời điểm yêu cầu thiết bị chụp ngay (đánh thức).', null=True)),
                ('wake_done_at', models.DateTimeField(blank=True, help_text='Thời điểm thiết bị xác nhận đã xử lý wake.', null=True)),
                ('sim_operator', models.CharField(blank=True, max_length=64)),
                ('sim_number', models.CharField(blank=True, max_length=32)),
                ('sim_iccid', models.CharField(blank=True, max_length=32)),
                ('sim_signal_dbm', models.IntegerField(blank=True, null=True)),
                ('battery_percent', models.IntegerField(blank=True, null=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=3, help_text='Điện áp tổng của khối pin (V).', max_digits=6, null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('cell_voltages', models.JSONField(blank=True, default=list)),
                ('solar_voltage', models.DecimalField(blank=True, decimal_places=3, help_text='Điện áp tấm pin mặt trời (V).', max_digits=6, null=True)),
                ('solar_percent', models.IntegerField(blank=True, help_text='Mức thu năng lượng solar ước tính (%).', null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Lần cuối thiết bị check-in.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.camera')),
            ],
            options={
                'verbose_name': 'Camera device',
                'verbose_name_plural': 'Camera devices',
            },
        ),
    ]
