# Generated by Django 4.2.30 on 2026-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_media_options_alter_mediaarchive_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradevice',
            name='humidity_percent',
            field=models.IntegerField(blank=True, help_text='Độ ẩm môi trường (%).', null=True),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='sim_query_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='sim_updated_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối thông tin SIM được cập nhật.', null=True),
        ),
    ]
