# Generated by Django 4.2.9 on 2026-07-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cameradevice_humidity_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('aperture', models.CharField(blank=True, max_length=16)),
                ('shutter_speed', models.CharField(blank=True, max_length=16)),
                ('exposure_compensation', models.DecimalField(blank=True, decimal_places=1, help_text='Bù phơi sáng (EV), -5.0 … +5.0, bước 1/3.', max_digits=3, null=True)),
                ('exposure_mode', models.CharField(blank=True, help_text='Num phơi sáng vật lý; chỉ đọc từ camera.', max_length=8)),
                ('autofocus', models.BooleanField(default=True)),
                ('focus_mode', models.CharField(blank=True, choices=[('af_s', 'AF-S (single)'), ('af_c', 'AF-C (continuous)'), ('af_a', 'AF-A (auto)'), ('mf_fixed', 'Manual (fixed)'), ('mf_selection', 'Manual (selection)')], max_length=16)),
                ('image_format', models.CharField(choices=[('jpeg_basic', 'JPEG Basic'), ('jpeg_normal', 'JPEG Normal'), ('jpeg_fine', 'JPEG Fine'), ('raw', 'RAW (NEF)'), ('raw_jpeg_basic', 'RAW + JPEG Basic'), ('raw_jpeg_normal', 'RAW + JPEG Normal'), ('raw_jpeg_fine', 'RAW + JPEG Fine')], default='raw_jpeg_fine', max_length=20)),
                ('image_size', models.CharField(choices=[('large', 'Large (6000×4000)'), ('medium', 'Medium (4496×3000)'), ('small', 'Small (2992×2000)')], default='large', max_length=8)),
                ('white_balance', models.CharField(choices=[('auto', 'Auto'), ('daylight', 'Daylight'), ('fluorescent', 'Fluorescent'), ('tungsten', 'Tungsten'), ('flash', 'Flash'), ('cloudy', 'Cloudy'), ('shade', 'Shade'), ('preset', 'Preset (manual)')], default='auto', max_length=16)),
                ('capture_mode', models.CharField(choices=[('single', 'Single'), ('burst', 'Burst'), ('continuous_low', 'Continuous (low)'), ('timer', 'Timer'), ('quick_remote', 'Quick remote'), ('delayed_remote', 'Delayed remote'), ('quiet', 'Quiet')], default='single', max_length=16)),
                ('capture_target', models.CharField(choices=[('client', 'Client (tải về server)'), ('memory_card', 'Memory card (thẻ nhớ)')], default='client', max_length=16)),
                ('long_exposure_nr', models.BooleanField(default=False)),
                ('high_iso_nr', models.CharField(choices=[('off', 'Off'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='off', max_length=8)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('applied', models.JSONField(blank=True, default=dict)),
                ('last_request_id', models.CharField(blank=True, max_length=64)),
                ('last_command_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.camera')),
            ],
            options={
                'verbose_name': 'Camera settings',
                'verbose_name_plural': 'Camera settings',
            },
        ),
    ]
