# Generated by Django 4.2.9 on 2026-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_camerasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='mqtt_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
