# Generated by Django 4.2.9 on 2026-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_camera_mqtt_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_model',
            field=models.CharField(choices=[('nikon_d5300', 'Nikon D5300'), ('nikon_d3500', 'Nikon D3500'), ('nikon_d7500', 'Nikon D7500'), ('nikon_z50', 'Nikon Z50'), ('canon_200d', 'Canon EOS 200D'), ('canon_90d', 'Canon EOS 90D'), ('generic', 'Generic (other)')], db_index=True, default='generic', max_length=32, verbose_name='Camera model'),
        ),
    ]
