# Generated by Django 4.2.9 on 2026-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_camera_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerasettings',
            name='long_exposure_nr',
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='focus_switch',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='long_exp_nr',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='aperture',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='autofocus',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='capture_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='capture_target',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='exposure_compensation',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='exposure_mode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='focus_mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='high_iso_nr',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='image_format',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='image_size',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='iso',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='shutter_speed',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='camerasettings',
            name='white_balance',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
