# Generated by Django 4.2.9 on 2026-07-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_camerasettings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='liveview_af',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
