# Generated by Django 4.2.30 on 2026-07-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_liveview_af'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Người liên hệ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='site',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa điểm'),
        ),
        migrations.AddField(
            model_name='site',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dự án'),
        ),
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Bật thông báo')),
                ('battery_low_pct', models.PositiveIntegerField(default=20, verbose_name='Pin yếu (% cảnh báo)')),
                ('battery_critical_pct', models.PositiveIntegerField(default=10, verbose_name='Pin nguy hiểm (%)')),
                ('signal_weak_dbm', models.IntegerField(default=-90, verbose_name='Tín hiệu yếu (dBm)')),
                ('offline_minutes', models.PositiveIntegerField(default=30, verbose_name='Cảnh báo offline sau (phút)')),
                ('temperature_high_c', models.IntegerField(default=50, verbose_name='Nhiệt độ cao (°C)')),
                ('daily_photo_min', models.PositiveIntegerField(default=0, verbose_name='Số ảnh tối thiểu/ngày (0=tắt)')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Email nhận cảnh báo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='core.camera')),
            ],
            options={
                'verbose_name': 'Alert settings',
                'verbose_name_plural': 'Alert settings',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client', verbose_name='Khách hàng'),
        ),
        migrations.CreateModel(
            name='VideoRender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('fps', models.PositiveIntegerField(default=24, verbose_name='FPS')),
                ('resolution', models.CharField(choices=[('3840x2160', '4K (3840×2160)'), ('1920x1080', 'Full HD (1920×1080)'), ('1280x720', 'HD (1280×720)'), ('854x480', 'SD (854×480)')], default='1920x1080', max_length=16, verbose_name='Độ phân giải')),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('output_key', models.CharField(blank=True, max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_renders', to='core.camera')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_renders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video render',
                'verbose_name_plural': 'Video renders',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['camera', '-created_at'], name='core_videor_camera__1e08ce_idx'), models.Index(fields=['status'], name='core_videor_status_9f7083_idx')],
            },
        ),
    ]
