# Generated by Django 4.2.30 on 2026-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_alertsettings_videorender'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorender',
            name='frame_interval',
            field=models.PositiveIntegerField(default=0, help_text='Lấy 1 ảnh mỗi N giây. 0 = lấy tất cả ảnh.', verbose_name='Tần suất (giây)'),
        ),
    ]
