# Generated by Django 4.2.30 on 2026-07-28 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_videorender_frame_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Client Admin'), ('member', 'Client Member')], default='member', max_length=10)),
                ('can_download', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.client')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client membership',
                'verbose_name_plural': 'Client memberships',
                'unique_together': {('user', 'client')},
            },
        ),
    ]
