# Generated by Django 4.2.30 on 2026-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_usercameraaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradevice',
            name='cm4_last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối CM4 gửi Telemetry / thực thi nhiệm vụ.', null=True),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='cm4_power_state',
            field=models.CharField(choices=[('off', 'OFF (Đang ngủ)'), ('powering_on', 'Đang khởi động'), ('running', 'Hoạt động'), ('shutting_down', 'Đang tắt nguồn')], db_index=True, default='off', max_length=20),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='esp32_firmware',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='esp32_last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Lần cuối ESP32-S3 Always-On check-in (xác định Online/Offline trạm).', null=True),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='sim_active_node',
            field=models.CharField(default='esp32', help_text='Nút đang giữ module SIM (esp32 via UART / cm4 via USB).', max_length=16),
        ),
    ]
