# Generated by Django 4.2.30 on 2026-08-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_videorender_expired_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradevice',
            name='schedule_enabled',
            field=models.BooleanField(default=False, help_text='Bật/Tắt lịch chụp theo khung giờ.'),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='work_end_time',
            field=models.CharField(default='18:00', help_text='Giờ kết thúc chụp (HH:MM).', max_length=5),
        ),
        migrations.AddField(
            model_name='cameradevice',
            name='work_start_time',
            field=models.CharField(default='06:00', help_text='Giờ bắt đầu chụp (HH:MM).', max_length=5),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_model',
            field=models.CharField(choices=[('nikon_d5300', 'Nikon D5300'), ('nikon_d3500', 'Nikon D3500'), ('nikon_d7100', 'Nikon D7100'), ('nikon_d7500', 'Nikon D7500'), ('nikon_z50', 'Nikon Z50'), ('canon_200d', 'Canon EOS 200D'), ('canon_90d', 'Canon EOS 90D'), ('generic', 'Generic (other)')], db_index=True, default='generic', max_length=32, verbose_name='Camera model'),
        ),
    ]
