# Generated by Django 4.2.30 on 2026-08-10 02:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cameradevice_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='alertsettings',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='CameraSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Khung giờ chụp', max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('start_time', models.CharField(default='07:00', help_text='Giờ bắt đầu (HH:MM)', max_length=5)),
                ('end_time', models.CharField(default='17:00', help_text='Giờ kết thúc (HH:MM)', max_length=5)),
                ('interval_sec', models.PositiveIntegerField(default=300, help_text='Chu kỳ chụp (giây)')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Các ngày trong tuần [1..7]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.camera')),
            ],
            options={
                'verbose_name': 'Alert settings',
                'verbose_name_plural': 'Alert settings',
            },
        ),
    ]
