# Generated by Django 4.2.30 on 2026-08-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_videorender_output_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertsettings',
            options={'verbose_name': 'Alert settings', 'verbose_name_plural': 'Alert settings'},
        ),
        migrations.AlterModelOptions(
            name='cameraschedule',
            options={'ordering': ('start_time',), 'verbose_name': 'Lịch chụp Camera', 'verbose_name_plural': 'Lịch chụp Camera'},
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
