# Generated by Django 4.2.30 on 2026-08-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_fix_camera_schedule_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaarchive',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videorender',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
