# Generated by Django 4.2.30 on 2026-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_job_processing_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameradevice',
            name='force_power_on',
            field=models.BooleanField(default=False, help_text='Cờ cưỡng bức bật CM4 từ Web UI (giữ CM4 luôn chạy, không tắt sau khi chụp).'),
        ),
    ]
