"""
Django settings for autotimelapse project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u_am=8by79nhqo9p@msu21tm5v$nwlrvau@d3(z)qx-fog$%a!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '1') == '1'

_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '*').strip()
_hosts_list = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
if '*' in _hosts_list:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = _hosts_list


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # project
    'core',
    'mqtt_service',
    # API
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 60,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # sau Session, trước Common
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'autotimelapse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_perms',
            ],
        },
    },
]

WSGI_APPLICATION = 'autotimelapse.wsgi.application'

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Auth redirects
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'

# ── Session security ──────────────────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 60 * 60 * 2   # Default 2 giờ (override bằng set_expiry)

# ── Reverse proxy / HTTPS ─────────────────────────────────────────────────────
# Tin tưởng X-Forwarded-Proto từ reverse proxy để Django nhận ra request là HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cho phép CSRF từ localhost + domain cấu hình trong env
_csrf_extra = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
] + _csrf_extra


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Override DATABASES trong local_settings.py cho từng môi trường

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'autotimelapse'),
        'USER': os.environ.get('DB_USER', 'atl_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'atl_pass_2026'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# ── SeaweedFS / S3 object storage ─────────────────────────────────────────────
# Backend + SeaweedFS chạy chung 1 VPS. Django KHÔNG serve file, chỉ tạo
# presigned URL để browser tải trực tiếp từ SeaweedFS (giảm tải Django).
# Override credential thật trong local_settings.py.
SEAWEED = {
    "ENDPOINT_URL": os.environ.get('SEAWEED_ENDPOINT_URL', 'http://127.0.0.1:8333'),   # S3 gateway nội bộ
    "PUBLIC_ENDPOINT_URL": os.environ.get('SEAWEED_PUBLIC_ENDPOINT_URL', '') or None,   # URL public cho presigned (browser/device)
    "ACCESS_KEY": "api-tl-key",
    "SECRET_KEY": "ApiTL2026SecretXyz",
    "BUCKET": "media",
    "REGION": "us-east-1",                       # SeaweedFS bỏ qua nhưng boto3 cần
    "PRESIGN_EXPIRE": 3600,                       # URL ảnh hết hạn sau 1 giờ
    "ADDRESSING_STYLE": "path",                   # SeaweedFS dùng path-style
}


# ── Redis: cache + Celery broker (hệ thống lớn, tác vụ nặng chạy nền) ──────────
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "TIMEOUT": 300,
    }
}

# Celery: nén ZIP tải hàng loạt chạy nền, KHÔNG block request.
CELERY_BROKER_URL = f"{REDIS_URL}/0"
CELERY_RESULT_BACKEND = f"{REDIS_URL}/2"
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TIME_LIMIT = 60 * 30          # cứng 30 phút / task
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 25
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50    # tránh rò rỉ bộ nhớ
CELERY_TASK_TRACK_STARTED = True
CELERY_TIMEZONE = "Asia/Ho_Chi_Minh"

# ── Celery Queue Routing ─────────────────────────────────────────────────────
# archive: nén ZIP ảnh (I/O nặng, ưu tiên cao)
# render:  ffmpeg render video (CPU cực nặng, chạy riêng biệt, concurrency=1)
# default: tác vụ chung (cleanup, beat tasks, ...)
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_ROUTES = {
    "core.tasks.build_media_archive":      {"queue": "archive"},
    "core.tasks.cleanup_expired_archives": {"queue": "default"},
    "core.tasks.render_timelapse_video":   {"queue": "render"},
}

# ── MQTT: giao tiếp với trạm camera (Mosquitto + Dynamic Security) ──────────
import os as _os
MQTT_BROKER = _os.environ.get("MQTT_BROKER", "127.0.0.1")
MQTT_PORT = int(_os.environ.get("MQTT_PORT", "1883"))
MQTT_USER = _os.environ.get("MQTT_USER", "admin")
MQTT_PASS = _os.environ.get("MQTT_PASS", "Admin@Mqtt2026")
MQTT_CLIENT_ID = _os.environ.get("MQTT_CLIENT_ID", "")          # rỗng → tự sinh
MQTT_SKIP_ACL_SETUP = _os.environ.get("MQTT_SKIP_ACL_SETUP", "0") == "1"
MQTT_ENABLED = _os.environ.get("MQTT_ENABLED", "1") == "1"

# Vòng đời file nén tải về (giờ). Hết hạn → xoá khỏi SeaweedFS.
MEDIA_ARCHIVE_TTL_HOURS = 24
MEDIA_ARCHIVE_MAX_ITEMS = 5000            # trần số ảnh 1 lần gom tải


# Load local overrides (secret, DB, DEBUG) — KHÔNG commit file này
try:
    from .local_settings import *  # noqa: F401,F403
except ImportError:
    pass


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'vi'   # mặc định tiếng Việt

LANGUAGES = [
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Load local_settings.py if available (override with environment settings)
try:
    from .local_settings import *
except ImportError:
    pass

